##################################################################################
#         Calls workflow from code repo
##################################################################################
name: Android - Release to Google Play TEST

on:
  workflow_dispatch:

jobs:
  get_vars:
    runs-on: ubuntu-latest
    outputs:
      APP_ID: ${{ steps.export_vars.outputs.APP_ID }}
      LFS_USED: ${{ steps.export_vars.outputs.LFS_USED }}
      DEPLOYMENT_NAME: ${{ steps.export_vars.outputs.DEPLOYMENT_NAME }}
      PARENT_DEPLOYMENT_NAME: ${{ steps.export_vars.outputs.PARENT_DEPLOYMENT_NAME }}
      PARENT_DEPLOYMENT_REPO: ${{ steps.export_vars.outputs.PARENT_DEPLOYMENT_REPO }}
      PARENT_DEPLOYMENT_BRANCH: ${{ steps.export_vars.outputs.PARENT_DEPLOYMENT_BRANCH }}
      ENCRYPTED: ${{ steps.export_vars.outputs.ENCRYPTED }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Code branch used
        run: |
          echo "App Code Branch: ${{ vars.APP_CODE_BRANCH }}"

      - name: Load .env File and Pass Variables
        id: export_vars
        run: |
          set -o allexport
          source actions.env
          set +o allexport
          echo "APP_ID=$APP_ID" >> $GITHUB_OUTPUT          
          echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" >> $GITHUB_OUTPUT
          echo "PARENT_DEPLOYMENT_NAME=$PARENT_DEPLOYMENT_NAME" >> $GITHUB_OUTPUT
          echo "PARENT_DEPLOYMENT_REPO=$PARENT_DEPLOYMENT_REPO" >> $GITHUB_OUTPUT
          echo "PARENT_DEPLOYMENT_BRANCH=$PARENT_DEPLOYMENT_BRANCH" >> $GITHUB_OUTPUT
          echo "ENCRYPTED=$ENCRYPTED" >> $GITHUB_OUTPUT
          echo "LFS_USED=$LFS_USED" >> $GITHUB_OUTPUT

  call_reusable_workflow:
    needs: get_vars
    uses: IDEMSInternational/open-app-builder-actions/.github/workflows/android-release.yml@main
    with:
      APP_CODE_BRANCH: ${{ vars.APP_CODE_BRANCH }}
      APP_ID: ${{ needs.get_vars.outputs.APP_ID }}
      LFS_USED: ${{ needs.get_vars.outputs.LFS_USED  == 'true' }}
      DEPLOYMENT_NAME: ${{ needs.get_vars.outputs.DEPLOYMENT_NAME }}
      PARENT_DEPLOYMENT_NAME: ${{ needs.get_vars.outputs.PARENT_DEPLOYMENT_NAME }}
      PARENT_DEPLOYMENT_REPO: ${{ needs.get_vars.outputs.PARENT_DEPLOYMENT_REPO }}
      PARENT_DEPLOYMENT_BRANCH: ${{ needs.get_vars.outputs.PARENT_DEPLOYMENT_BRANCH }}
      ENCRYPTED: ${{ needs.get_vars.outputs.ENCRYPTED == 'true' }} 
    secrets:
      DEPLOYMENT_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}  
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}  
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}  
      ALIAS: ${{ secrets.ALIAS }}  
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}  
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}  
      GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}  

