##################################################################################
#         Calls workflow from code repo
##################################################################################
name: Android - Release to Google Play TEST

on:
  workflow_dispatch:

jobs:
  get_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Code branch used
        run: |
          echo "App Code Branch: ${{ vars.APP_CODE_BRANCH }}"


      - name: Load .env File and Pass Variables
        run: |
          set -o allexport
          source actions.env
          set +o allexport
          echo "APP_ID=$APP_ID" >> $GITHUB_ENV
          echo "LFS_USED=$LFS_USED" >> $GITHUB_ENV
          echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" >> $GITHUB_ENV
          echo "PARENT_DEPLOYMENT_NAME=$PARENT_DEPLOYMENT_NAME" >> $GITHUB_ENV
          echo "PARENT_DEPLOYMENT_REPO=$PARENT_DEPLOYMENT_REPO" >> $GITHUB_ENV
          echo "PARENT_DEPLOYMENT_BRANCH=$PARENT_DEPLOYMENT_BRANCH" >> $GITHUB_ENV
          echo "ENCRYPTED=$ENCRYPTED" >> $GITHUB_ENV

      - name: Call Reusable Workflow
        uses: IDEMSInternational/open-app-builder-actions/.github/workflows/android-release.yml@master
        with:
          APP_CODE_BRANCH: ${{ vars.APP_CODE_BRANCH }}
          APP_ID: ${{ env.APP_ID }}
          LFS_USED: ${{ env.LFS_USED }}          
          DEPLOYMENT_NAME: ${{ env.DEPLOYMENT_NAME }}
          PARENT_DEPLOYMENT_NAME: ${{ env.PARENT_DEPLOYMENT_NAME }}
          PARENT_DEPLOYMENT_REPO: ${{ env.PARENT_DEPLOYMENT_REPO }}
          PARENT_DEPLOYMENT_BRANCH: ${{ env.PARENT_DEPLOYMENT_BRANCH }}
          ENCRYPTED: ${{ env.ENCRYPTED }}
  
